default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL") { "postgresql://postgres:@localhost:5432/staj_proje_development" } %>

test:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL") { "postgresql://postgres:@localhost:5432/staj_proje_test" } %>

production:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL") %>
